### ISSUE TITLE
ODC down

### ISSUE THREAD

**Issue by joevstaasodp** [C4IROcean/OceanDataConnector#24]
I'm not able to authenticate. Tried some hours ago as well as right now. Also experiencing problems with auth in the app (Explorer etc.)-
https://dask.prod.oceandata.xyz/
![image](https://user-images.githubusercontent.com/56582228/236488246-3a78a2a5-18ed-46a4-b8f5-c76d6e614cd2.png)

**Comment by thomafred** [comment]
Issue likely related to ongoing instability in Azure Functions. We are also seeing our azure monitoring trigger on the auth-service intermittently.

So far we have not deemed this a very big issue, as we have not received any feedback that suggests otherwise. It is therefore very good that you submitted this report :)

The ODC (and other services) seem to be back up, so I am closing the issue as "Won't Fix", as this is not an ODC issue this time around, but an auth-issue.
